version: '3.2'

services:
  grafana:
    image: "grafana/grafana:8.2.0"
    expose:
      - "8001"
      - "8002"
    networks:
      - web1
      - web2
    restart: unless-stopped

  nginx1:
    image: "nginx:latest"
    ports: 
      - "8001:80"
    networks:
      - web1
    links:
      - "grafana:grafana"
    volumes:
      - type: bind
        source: ./nginx1/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    restart: unless-stopped

  nginx2:
    image: "nginx:latest"
    ports:
      - "8002:80"
    networks:
      - web2
    links:
      - "grafana:grafana"
    volumes:
      - type: bind
        source: ./nginx1/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    restart: always


networks:
  web1:
  web2:

volumes:
  nginxconf:
